---
- hosts: all
  become: true
  become_user: root
  tasks:
    #- name: Verificar conectividad (ping)
      #ansible.builtin.ping:

    - name: Obtener el usuario actual
      ansible.builtin.shell: whoami
      register: quien

    - name: Mostrar resultado del whoami
      ansible.builtin.debug:
        var: quien.stdout
